var { instagramDb } = require('./appmodel');
var { Schema } = require('mongoose');

var datePickerFullprofileSchema = new Schema({
    username: { type: String, required: true},
    bio: String,
    followers: Number,
    following: Number,
    userId: String,
    fullname: String,
    profpic: String,
    availableVideo: Number,
    totalUniquePost: Number,
    totalLike: Number,
    totalComment: Number,
    totalView: Number,
    likeRate: Number,
    commentRate: Number,
    engagementRate: Number,
    likePerPost: Number,
    commentPerPost: Number,
    engagementPerPost: Number,
    postPerDay: Number,
    postPerWeek: Number,
    postPerMonth: Number,
    mostWord: Schema.Types.Mixed,
    mostType: Schema.Types.Mixed,
    mostTag: Schema.Types.Mixed,
    mostMention: Schema.Types.Mixed,
    likeByDate: Schema.Types.Mixed,
    commentByDate: Schema.Types.Mixed,
    postByDate: Schema.Types.Mixed,
    postByDay: Schema.Types.Mixed,
    viewByDay: Schema.Types.Mixed,
    viewByDate: Schema.Types.Mixed,
    engByDay: Schema.Types.Mixed,
    engRateByDay: Schema.Types.Mixed,
    postHeatMap: Schema.Types.Mixed,
    engHeatMap: Schema.Types.Mixed,
    topPost: Schema.Types.Mixed,
    location: Schema.Types.Mixed,
    averageAllByDay: Schema.Types.Mixed,
    duetEngagementRate: Schema.Types.Mixed,
    website: String,
    is_verified: Boolean,
    is_business_account: Boolean,
    is_private: Boolean,
    is_professional_account: Boolean,
    is_joined_recently: Boolean,
    category : Schema.Types.Mixed,
    userType: Schema.Types.Mixed,
    email: String,
    dateFrom: Number,
    dateTo: Number,
},
{ timestamps: true }
);
var datePickerFullProfile = instagramDb.model(
  "datePickerProfileInstagram",
  datePickerFullprofileSchema,
  "apiDatePickerProfile"
);

module.exports = datePickerFullProfile;